### PR TITLE
Display relative calculations

### PR DESCRIPTION
**Pull request by Jamdan2**
Only display calculations that are supported by that type of metric. For instance, a text metric will no longer give you the option to find it's maximum 😆

### CODE REVIEW

**Comment by Jamdan2** [comment]
Sure, all we need to do is add boolean to the types array in avarage. Should we call it something else though? maybe percent true? Idk anything about data analysis 🤷‍♂️

**Comment by will-hou** [comment]
Later on, it might be nice if we could also display text-based information like "best autonomous" and data on its reliability

**Comment by Jamdan2** [comment]
Will make a separate pr for implementing more non-numeric calculations 👍

**Comment by andrewda** [comment]
I _think_ average still makes the most sense for boolean values, and would be good just for consistency's sake.

**Comment by Jamdan2** [comment]
Alright

**Comment by Jamdan2** [comment]
Oh wow thats so cool it does!

**Comment by Jamdan2** [comment]
I think I fixed that

**Comment by andrewda** [comment]
The checkboxes seem to not be persistent. After I close the TableSettings dialog, the correct fields show up, but when I reopen the dialog all the boxes are unchecked.

**Comment by Jamdan2** [comment]
Yeah that needs to be fixed

**Comment by Jamdan2** [comment]
Everyone good with this?

**Pull request merged**
