### PR TITLE
Remake table as scrolling

### PR DESCRIPTION
**Pull request by Jamdan2**
Remake table in a scrolling fashion, as opposed to pagination. Goals for table:

- [x] Scrolling
- [x] Fixed header and rows
- [x] Sorting by column
- [ ] Tool tips to view for sub-stringed text
- [x] Search bar
- [x] Filter by column
- [x] Pretty up table view page

### CODE REVIEW

**Comment by Jamdan2** [comment]
#28 is fixed by this

**Comment by andrewda** [comment]
Wow this looks awesome!! 😮 ✨ 💖

**Comment by andrewda** [comment]
_Small_ nitpick I have is that I can't scroll when my mouse is in the header or the side with the team/scout numbers (anywhere grey). It'd be very nice to be able to scroll down/to the side there.

**Comment by Jamdan2** [comment]
Tooltips not a thing, but its time to move on anyway. I will add an issue and work on it at a later time

**Pull request merged**
